[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = """
      default-src 'self' https://zgoxbcxwlndzloyonbon.supabase.co;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.klaviyo.com https://static-tracking.klaviyo.com https://www.googletagmanager.com https://www.google-analytics.com https://snap.licdn.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: https://www.google-analytics.com https://px.ads.linkedin.com;
      font-src 'self' data:;
      connect-src 'self' https://zgoxbcxwlndzloyonbon.supabase.co wss://zgoxbcxwlndzloyonbon.supabase.co https://formsubmit.co https://*.klaviyo.com https://*.google-analytics.com https://*.linkedin.com;
      frame-ancestors 'none';
      form-action 'self' https://formsubmit.co;
    """